In [68]:
import math as m
import sympy as s
x = s.Symbol('x')
eq = s.sqrt(x)-s.cos(x)
ans = s.diff(eq).evalf(subs={x:2})
print("True Value = ",ans)
a = m.sqrt(2+0.3)-m.cos(2+0.3)
b = m.sqrt(2)-m.cos(2)
apprx = (a-b)/0.3
print("Approximatly value = ",apprx)
print("True Error = ",abs(apprx-ans))

True Value =  1.26285081741896
Approximatly value =  1.1749690372329877
True Error =  0.0878817801859677


# Regula Falsi

In [71]:
def f(x):
    return m.exp(-2*x)+4*x**2-36
def Regulafalsi(xL,xU):
    for i in range(15):
        xR = ((xL*f(xU))-(xU*f(xL)))/(f(xU)-f(xL))
        print("  ",i,"\t\t",round(xL,4),"\t",round(xU,4),"\t",round(xR,4),"\t",abs(round(f(xR),4)))
        
        if f(xR)<0:
            xU = xR
        else:
            xL = xR
        if abs(f(xR))<= 0.0001:
            break
print("==========================================================================")
print("                             Regula Falsi Method")
print("==========================================================================")
print("Iteration\txL\t\txU\t\txR\t\tTolarance")
Regulafalsi(1,2)

                             Regula Falsi Method
Iteration	xL		xU		xR		Tolarance
   0 		 1 	 2 	 3.6815 	 18.2155
   1 		 3.6815 	 2 	 2.8796 	 2.8274
   2 		 3.6815 	 2.8796 	 2.9874 	 0.2994
   3 		 3.6815 	 2.9874 	 2.9986 	 0.0307
   4 		 3.6815 	 2.9986 	 2.9998 	 0.0031
   5 		 3.6815 	 2.9998 	 2.9999 	 0.0003
   6 		 3.6815 	 2.9999 	 2.9999 	 0.0


# Muller Method

In [62]:
import math as m
import sympy as s
def f(x):
    return 2*x-m.exp(x)+(3*m.cos(x))
def muller(x0,x1,x2): 
    for i in range(100):
        h1=x1-x0
        h2=x2-x1
        d1=(f(x1)-f(x0))/h1
        d2=(f(x2)-f(x1))/h2
        C=f(x2)
        A= (d2 - d1)/(h1+h2)
        #print("value of A is:",A)
        B=a*h2+d1
        #print("value of B is:",B)
        sa=m.sqrt(B**2-4*A*C)
        if B>0:        
            xr=x2-(2*C)/(B+sa)   
        else:
            xr=x2-(2*C)/(B-sa)
        tol = abs((xr-x2)/xr)
        print("  ",i,"\t\t",round(x0,4),"\t",round(x1,4),"\t",round(x2,4),"\t",round(xr,4),"\t",round(tol,5))
        if  tol <= 0.0001:
            break
        if xr<x1:
            x2=x1
            x1=xr
        else:
            x0=x1
            x1=xr
print("==========================================================================")
print("                             Muller's Method")
print("==========================================================================")
print("Iteration\tx0\t\tx1\t\tx2\t\txR\tTolarance")       
muller(-2,0,2)


                             Muller's Method
Iteration	x0		x1		x2		xR	Tolarance


NameError: name 'a' is not defined

In [30]:
import math as m
def f(x):
    return 2*x-m.exp(x)+(3*m.cos(x))
def muller(x0,x1,x2):
    for i in range(200):
        d1=f(x0)-f(x2)
        d2=f(x1)-f(x2)
        c=f(x2)
        h1=x0-x2
        h2=x1-x2
        A=(h2*d1-h1*d2)/(h1*h2*(x1-x0))
        #print("Value of A is",A)
        B=((h2**2*d1)-(h1**2*d2))/(h1*h2*(h1-h2))
        #print("Value of B is",B)
        if(B<0):
            xr=x2-2*f(x2)/(B-abs(m.sqrt(B**2-4*A*c)))
        else:
            xr=x2-2*f(x2)/(B+abs(m.sqrt(B**2-4*A*c)))
        tol = abs(xr-x2)
        if  tol < 0.00001:
            break
        if(xr<x1):
            x2=x1
            x1=xr
        else:
            x0=x1
            x1=xr
        print(i,"value of root is",xr)
            
muller(-1.8,0,2.1)

0 value of root is 2.7388414660706752
1 value of root is 2.599066322423342
2 value of root is 3.50135955025601
3 value of root is 3.37062810523123
4 value of root is 4.2703473959905764
5 value of root is 4.162510524271303
6 value of root is 5.027979400610356
7 value of root is 4.928816784484455
8 value of root is 5.779967932522761
9 value of root is 5.688583562532376
10 value of root is 6.537214857877968
11 value of root is 6.448126666173437
12 value of root is 7.303412210674531
13 value of root is 7.21329927539794
14 value of root is 8.077296234698865
15 value of root is 7.9850805991648395
16 value of root is 8.856007896591034
17 value of root is 8.761992429613496
18 value of root is 9.637166382473891
19 value of root is 9.542041214478568
20 value of root is 10.419389659020302
21 value of root is 10.323711563549985
22 value of root is 11.202047298530807
23 value of root is 11.10612982864238
24 value of root is 11.98489604074805
25 value of root is 11.888879174142911
26 value of root i

In [61]:
import numpy as np
def f(x):
    return 2*x - np.exp(x) + 3*np.cos(x)
def muller( x0, x1, x2):
    for i in range(100):
        h1 = x1 - x0
        h2 = x2 - x1
        d1 = (f(x1) - f(x0)) / h1
        d2 = (f(x2) - f(x1)) / h2
        d = (d2 - d1) / (h2 + h1)
        b = d2 + h2*d
        D = np.sqrt(b**2 - 4*f(x2)*d)
        if abs(b-D) < abs(b+D):
            E = b + D
        else:
            E = b - D
        h = -2*f(x2) / E
        p = x2 + h
        print("  ",i,"\t\t",round(x0,5),"\t",round(x1,5),"\t",round(x2,5),"\t",round(p,5),"\t",round(abs(h),5))
        if abs(h) < 0.00001:
            break
        x0 = x1
        x1 = x2
        x2 = p
        
    
print("==========================================================================")
print("                             Muller's Method")
print("==========================================================================")
print("Iteration\tx0\t\tx1\t\tx2\t\txR\t\tTolarance")  
muller(-2, 0, 2)

                             Muller's Method
Iteration	x0		x1		x2		xR		Tolarance
   0 		 -2 	 0 	 2 	 1.12278 	 0.87722
   1 		 0 	 2 	 1.12278 	 1.23721 	 0.11443
   2 		 2 	 1.12278 	 1.23721 	 1.2397 	 0.00249
   3 		 1.12278 	 1.23721 	 1.2397 	 1.23971 	 1e-05
   4 		 1.23721 	 1.2397 	 1.23971 	 1.23971 	 0.0


# A(BC)=AB+BC

In [45]:
import numpy as np
A= np.array([[1,2,3],[4,5,6]])
B= np.array([[2,3],[4,5],[6,7]])
C = np.array([[9,3],[1,2]])
result1 = np.array([[0,0],[0,0],[0,0]])
result = np.array([[0,0],[0,0]])
result2 = np.array([[0,0],[0,0],[0,0]])
result3 = np.array([[0,0],[0,0]])
print("A(BC) = AB + BC")
#BC
for i in range(3):
    for j in range(2):
        for k in range(2):
            result1[i,j] +=B[i,k]*C[k,j]
#A(BC)
for i in range(2):
    for j in range(2):
        for k in range(3):
            result[i,j] += A[i,k]*result1[k,j]
print("A(BC)")
print(result)
#AB
for i in range(2):
    for j in range(2):
        for k in range(3):
            result3[i,j] +=A[i,k]*B[k,j]
print("AB")
print(result3)
print("BC")
print(result1)
print("AB + BC is not possible because the size of the matrix is not same")


A(BC) = AB + BC
A(BC)
[[286 152]
 [655 350]]
AB
[[28 34]
 [64 79]]
BC
[[21 12]
 [41 22]
 [61 32]]
AB + BC is not possible because the size of the matrix is not same


In [21]:
import matplotlib.pyplot as plt
import numpy as np

def f(x):
    return 2*x - np.exp(x) + 3*np.cos(x)

x = np.linspace(-5, 5, 1000)
y = f(x)
plt.plot(x, y)
plt.grid()
plt.show()